language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
script:
  - npm i && tns platform add android && tns build android
  - tns platform add ios && tns build ios
